### ISSUE TITLE
C language family categorisation

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/Programming2017#1]
"_My only (very minor) gripe is that, while C and C++ share a lot from the PL and pedagogic perspective, I would not lump C# into that bucket. From the PL perspective, it seems much closer to Java. Culturally, I'm not sure, but it does not seem to share much with C/C++ beyond the initial letter of the name._"

**Comment by JamesHDavenport** [comment]
Added (yet another) footnote. It's complicated. I'll ask Ellen for the raw data.

**Comment by JamesHDavenport** [comment]
Raw data isn't helpful, footnote expanded.  We have the individual languages as well, so readers can play for themselves.
