### ISSUE TITLE
Size of figures

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/Programming2017#14]
Due to having extra space (and for readability), are we able to make the figures slightly larger?

**Comment by JamesHDavenport** [comment]
Ellen probably can - I am not sure I can, but I'll try to look later today. Any particular figure you're thinking of? I don't think a 10% blowup all round, say, would really help much., and be a *** with the page layout.

**Comment by JamesHDavenport** [comment]
I've pushed a JHD version, where Figure 1 is enlarged 30%. 'diff' will show you how I did it :)
James

**Comment by JamesHDavenport** [comment]
Congratulations on reading my hack!

**Comment by tomcrick** [comment]
Thank you!
