### ISSUE TITLE
More analysis required?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/Programming2017#2]
"_I have no real idea what such papers are supposed to be like. If just supplying data is OK, then they did a great job. If some analysis is usual, I didn't see much and would consider this paper as having fallen down on this point._"

**Comment by JamesHDavenport** [comment]
It's not clear what more analysis we could do: I would claim we ARE a fact-reporting paper.

**Comment by JamesHDavenport** [comment]
We are largely a fact-reporting paper, so I'm closing this.
