### ISSUE TITLE
Better explain UK HE terminology

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/Programming2017#3]
"_I also learned some nuances of the UK higher ed system that I did not know prior to my reading. However, the explanation of “low tariff” meaning was not clear to me in terms of how it would compare to institutions in other countries. I also am not sure what “leagues tables” mean on page 16_"

**Comment by JamesHDavenport** [comment]
I've added a footnote to page 16 on league tables. I'm not sure how to respond to the other question. @Tom, do you have an answer to that one? We can't quote examples (even if we wanted to) as the list is secret. Perhaps easier to say what 'high tariff' means.

**Comment by JamesHDavenport** [comment]
Tom to close
