### ISSUE TITLE
Clarity of institution type through the results

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/Programming2017#4]
"_It wasn’t clear to me at times what types of institutions contributed to specific parts of the survey results (e.g., top universities, to smaller colleges). This is mentioned in some places, but I did not see a constant thread across the survey questions were compared by the type of institution._"

**Comment by JamesHDavenport** [comment]
Humm. This shows some confusion, the 'lower tariff', aren't necessarily 'smaller colleges'. They're right, we aren't consistent here - doing the 'by type' only when it seems to matter. What should we do?
